services:

  postgres:
    image: postgres:15
    container_name: product-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: product-redis
    ports:
      - "6379:6379"